server:
  port: 8080 # 项目启动端口

spring:
  ai:
    deepseek:
      api-key: sk-b500bbe5d2be482caaf793cc9c46b28a
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8 # 用于控制生成文本的随机性和创造性